In [489]:
import numpy as np

In [490]:
arr = [[3,-1,2],[1,2,3],[2,-2,-1]]
n=3

In [491]:
u=[]
for i in range(n):
    a = [0 for  i in range(n)]
    a[i]=1
    u.append(a)

In [492]:
l =[]
for i in range(n):
    a = [0 for i in range(n)]
    l.append(a)

In [493]:
l,u

([[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [494]:
for i in range(n):
    l[i][0] = arr[i][0]

for j in range(1,n):
    u[0][j] = arr[0][j]/l[0][0]

In [495]:
l

[[3, 0, 0], [1, 0, 0], [2, 0, 0]]

In [496]:
u

[[1, -0.3333333333333333, 0.6666666666666666], [0, 1, 0], [0, 0, 1]]

In [497]:
for i in range(n):
    for j in range(1,n-1):
        l[i][j]=arr[i][j]
        for k in range(0,j):
            l[i][j] = l[i][j] -  l[i][k]*u[k][j]
        
for j in range(i+1,n):
        u[i][j] = arr[i][j]
        for k in range(0,i):
            u[i][j] = u[i][j]-l[i][k]*u[k][j]
        u[i][j] = u[i][j]/l[i][i]

l[n-1][n-1] = arr[n-1][n-1]
s=0
# for k in range(0,n):
#     l[n-1][n-1] = l[n-1][n-1]-l[n-1][k]*u[k][n-1] 
#     s-=l[n-1][k]*u[k][n-1]

In [498]:
arr[n-1][n-1]

-1

In [499]:
s

0

In [500]:
l

[[3, 0.0, 0], [1, 2.3333333333333335, 0], [2, -1.3333333333333335, -1]]

In [501]:
u

[[1, -0.3333333333333333, 0.6666666666666666], [0, 1, 0], [0, 0, 1]]

In [315]:
mt = np.matrix([[3,-1,2],[1,2,3],[2,-2,-1]])

In [316]:
mt

matrix([[ 3, -1,  2],
        [ 1,  2,  3],
        [ 2, -2, -1]])

In [317]:
import scipy as sp
import scipy.linalg

In [318]:
P,L,U  = sp.linalg.lu(mt)

In [319]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.33333333,  1.        ,  0.        ],
       [ 0.66666667, -0.57142857,  1.        ]])

In [320]:
U

array([[ 3.        , -1.        ,  2.        ],
       [ 0.        ,  2.33333333,  2.33333333],
       [ 0.        ,  0.        , -1.        ]])

In [321]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [334]:
L.dot(U)

array([[ 3., -1.,  2.],
       [ 1.,  2.,  3.],
       [ 2., -2., -1.]])

In [335]:
a = np.matrix([[3,0,0],[1,7/3,0],[2,-4/3,-1]])
b = np.matrix([[1,-1/3,2/3],[0,1,1],[0,0,1]])

In [336]:
a.dot(b)

matrix([[ 3., -1.,  2.],
        [ 1.,  2.,  3.],
        [ 2., -2., -1.]])

In [337]:
a = np.matrix([[3,0,0],[1,2,0],[2,-2,1]])
b = np.matrix([[1,-1/3,2/3],[0,1,1.5],[0,0,1]])

In [338]:
a.dot(b)

matrix([[ 3.        , -1.        ,  2.        ],
        [ 1.        ,  1.66666667,  3.66666667],
        [ 2.        , -2.66666667, -0.66666667]])